server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/frontend;

    # Frontend (React) - Catch-all for SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend (Laravel API)
    location /api {
        alias /var/www/backend/public;
        try_files $uri $uri/ @laravel;
    }

    location @laravel {
        rewrite /api/(.*)$ /api/$1 break;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Storage (Images/Uploads)
    location /storage {
        alias /var/www/backend/storage/app/public;
    }
}
